### ISSUE TITLE
✨ Add README

### ISSUE THREAD

**Issue by cmg-dev** [SteffenKn/s.to-api-client#1]
Ich will wissen was es kann :D

**Comment by SteffenKn** [comment]
Das ist ein einfacher Client für die s.to API.
Aber ich kann gerne noch eine Readme hinzufügen 😄

**Comment by SteffenKn** [comment]
Ich hab dir mal ne kleine Readme eingefügt von der Funktionalität die bisher unterstützt wird, ganz viel kann man damit nicht machen, aber für meine Anforderungen war es bisher ausreichend.
Wenn du weitere fragen hast kannst du ich gerne fragen 😄

**Comment by cmg-dev** [comment]
Sehr cool :) Dein Code ist cool. Ich hätte schon fast bock mal mein "Wissen" um Node.js auszugraben um eine CLI dafür zu bauen. Aber ich glaube da werde ich lange nicht zu kommen- alleine der späte Kommentar von mir hier belegt das 🙈
